name: Azure Functions Demo Deploy
on:
  push:
    tags-ignore:
      - "*"
permissions:
  id-token: write
env:
  APPNAME: ${{ github.actor }}-demo-functions
  RESOURCEGROUPNAME: ${{ github.actor }}-demo-rg
  APPDIR: app
jobs:
  prebuild:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-environment.outputs.name }}
      slot: ${{ steps.set-environment.outputs.slot }}
    steps:
      - id: set-environment
        run: |
          if [ $GITHUB_REF_NAME != "release" ]; then
            echo "name=production" >> $GITHUB_OUTPUTS
            echo "slot=stage" >> $GITHUB_OUTPUTS
          else
            echo "name=development" >> $GITHUB_OUTPUTS
            echo "slot=" >> $GITHUB_OUTPUTS
            HASH_VAL=$(echo ${GITHUB_REF} | sha256sum)
            echo "APPNAME=${APPNAME}-${HASH_VAL:0:8}"
          fi
  build:
    if: ${{!startsWith(github.ref, 'refs/heads/main')}}
    runs-on: ubuntu-latest
    needs:
      - prebuild
    environment: ${{ needs.prebuild.outputs.environment }}
    steps:
    - uses: actions/checkout@v3.1.0
      with:
          token: ${{secrets.MY_GITHUB_TOKEN}}
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
      with:
        # Set always-auth in npmrc.
        always-auth: false
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
        node-version: 16.x
    - name: Packaging
      run: |
        cd ${{ env.APPDIR }}
        npm install
        npm run build
    - name: Login to Azure
      uses: azure/login@v1.4.6
      continue-on-error: false
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTIONID }}
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.4.8
      with:
        # Name of the Azure Function App
        app-name: ${{ env.APPNAME }}
        # Path to package or folder. *.zip or a folder to deploy
        package: ${{ env.APPDIR }}
        slot-name: ${{ needs.prebuild.outputs.slot }}
    - name: Set appsettings
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az functionapp config appsettings set -name ${{ env.APPNAME }} --resource-group ${{ env.RESOURCEGROUPNAME }}
    - name: Failure notification
      uses: rtCamp/action-slack-notify@v2
      if: ${{ failure() }}
      env:
        SLACK_WEBHOOK:    ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_COLOR:      '#dc143c'  # 赤色の枠で通知が届く
        SLACK_MESSAGE:     |
          処理に失敗しました。
          ログを確認してください。

    - name: Succsess notification
      uses: rtCamp/action-slack-notify@v2
      if: ${{ success() }}
      env:
        SLACK_WEBHOOK:    ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_MESSAGE: |
          処理に成功しました。
  swap-slot:
    runs-on: ubuntu-22.04
    environment: production
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Login to Azure
      uses: azure/login@v1.4.6
      continue-on-error: false
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTIONID }}
    - name: Swap deploy slot
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az functionapp deployment slot swap --slot stage --name ${{ env.APPNAME }} --resource-group ${{ env.RESOURCEGROUPNAME }}
    - name: Failure notification
      uses: rtCamp/action-slack-notify@v2
      if: ${{ failure() }}
      env:
        SLACK_WEBHOOK:    ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_COLOR:      '#dc143c'  # 赤色の枠で通知が届く
        SLACK_MESSAGE:     |
          処理に失敗しました。
          ログを確認してください。

    - name: Succsess notification
      uses: rtCamp/action-slack-notify@v2
      if: ${{ success() }}
      env:
        SLACK_WEBHOOK:    ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_MESSAGE: |
          処理に成功しました。