name: Azure Functions Demo
on:
  push:
    branches-ignore:
      - main
permissions:
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - uses: actions/checkout@v3.1.0
      with:
          token: ${{secrets.MY_GITHUB_TOKEN}}
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
      with:
        # Set always-auth in npmrc.
        always-auth: false
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
        node-version: 16.x
    - name: Packaging
      run: |
        npm install
    - name: Select slot
      run: |
        if [[ ${GITHUB_REF} =~ refs\/heads\/release\/.* ]]; then
          echo "SLOT_NAME=" >> $GITHUB_ENV
        else
          echo "SLOT_NAME=stage" >> $GITHUB_ENV
        fi
    - name: Login to Azure
      uses: azure/login@v1.4.6
      continue-on-error: false
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTIONID }}
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.4.8
      with:
        # Name of the Azure Function App
        app-name: "quotto-demo-functions"
        # Path to package or folder. *.zip or a folder to deploy
        package: .
        slot-name: ${{env.SLOT_NAME}}
  switch-slot:
    runs-on: ubuntu-22.04
    if: startWith(github.ref,"refs/heads/release/")
    steps:
    - name: Switch deploy slot
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az functionsapp deployment slot swap --slot stage