name: Azure Functions Demo
on:
  push:
    branches-ignore:
      - main
env:
  APP_NAME: super-demo-func
permissions:
  id-token: write
jobs:
  build-and-deploy:
    if: ${{!startsWith(github.ref, 'refs/heads/release/')}}
    runs-on: ubuntu-latest
    environment: development
    steps:
    - uses: actions/checkout@v3.1.0
      with:
          token: ${{secrets.MY_GITHUB_TOKEN}}
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
      with:
        # Set always-auth in npmrc.
        always-auth: false
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
        node-version: 16.x
    - name: Packaging
      run: |
        npm install --production
    - name: Login to Azure
      uses: azure/login@v1.4.6
      continue-on-error: false
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTIONID }}
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.4.8
      with:
        # Name of the Azure Function App
        app-name: ${{ env.APP_NAME }}
        # Path to package or folder. *.zip or a folder to deploy
        package: .